import Home from "./Home/Home.jsx"
import SignUp from "./SignUp/SignUp.jsx"
import SignIn from "./signin/SignIn.jsx"
import Footer from "./footer/Footer.jsx"
import Product from "./Product/Product.jsx"
import Restaurants from "./Restaurants/Restaurants.jsx"
import Header from "./Header/Header.jsx"
import Cart from "./Product/Cart/Cart.jsx"
import Carousel from "./Carousel/Carousel.jsx"
import Profile from "./Profile/Profile.jsx"
import Checkout from "./checkout/Checkout.jsx"
import Payment from "./payment/Payment.jsx"
import Order from "./finalOrder/Order.jsx"
import Address from "./address/Address.jsx"

export const allFiles = { Address, Home, SignIn, SignUp, Footer, Profile, Payment, Order, Product, Cart, Checkout, Restaurants, Header, Carousel }